# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isagalaxytrack',
            name='galaxy_id',
            field=models.CharField(max_length=250),
        ),
    ]
