# Generated by Django 3.2.16 on 2022-10-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogi', '0002_IMPORT_DATA'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='molecular_framework',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='compound',
            name='predicted_lipidmaps_terms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
