# Generated by Django 3.2.16 on 2022-10-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mogi', '0004_auto_20221025_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchfragparam',
            old_name='metabolite_reference_standards',
            new_name='metabolite_reference_standard',
        ),
    ]
