# Generated by Django 3.2.16 on 2022-10-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mogi', '0005_rename_metabolite_reference_standards_searchfragparam_metabolite_reference_standard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fragspectratype',
            old_name='name',
            new_name='type',
        ),
    ]
