# Generated by Django 3.2.16 on 2022-10-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogi', '0006_rename_name_fragspectratype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragspectratype',
            name='short_nae',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='searchfragparam',
            name='metabolite_reference_standard',
            field=models.BooleanField(default=False, help_text='Include reference standard data in search(i.e. DMA assays where metabolite reference standard was measured)'),
        ),
        migrations.AlterField(
            model_name='searchfragparam',
            name='polarity',
            field=models.ManyToManyField(help_text='Choose polarities to search against', to='mogi.PolarityType'),
        ),
    ]
