# Generated by Django 3.2.16 on 2022-10-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogi', '0007_auto_20221025_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fragspectratype',
            old_name='short_nae',
            new_name='short_name',
        ),
        migrations.AlterField(
            model_name='searchfragparam',
            name='fragspectratype',
            field=models.ManyToManyField(help_text='Choose fragmentation spectra type', to='mogi.FragSpectraType', verbose_name='Fragmentation spectra type'),
        ),
        migrations.AlterField(
            model_name='searchfragparam',
            name='metabolite_reference_standard',
            field=models.BooleanField(default=False, help_text='Include reference standard data in search (i.e. DMA assays where metabolite reference standards were measured)'),
        ),
    ]
