# Generated by Django 3.2.18 on 2023-04-03 15:00

from django.db import migrations, models
import mogi.models.models_isa


class Migration(migrations.Migration):

    dependencies = [
        ('mogi', '0009_investigation_isa_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='isa_json',
        ),
        migrations.AddField(
            model_name='investigation',
            name='json_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=mogi.models.models_isa.isa_file_upload),
        ),
    ]
