# Generated by Django 3.2.18 on 2023-04-11 15:52

from django.db import migrations, models
import mogi.models.models_isa


class Migration(migrations.Migration):

    dependencies = [
        ('mogi', '0010_auto_20230403_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='investigation',
            name='isa_tab_zip',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=mogi.models.models_isa.isa_file_upload),
        ),
    ]
