# Generated by Django 3.2.18 on 2023-04-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mogi', '0012_exportisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='compound',
            name='organisms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
